# Generated by Django 4.1 on 2022-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default=" My Freakin Blog", max_length=225),
        ),
    ]
